
VERSION = '0.1.0'
PLUGIN_NAME = 'fido2-hmac'
HRP_IDENTITY = 'age-plugin-%s-' % (PLUGIN_NAME)
HRP_RECIPIENT = 'age1-%s-' % (PLUGIN_NAME)
IDENTITY_FORMAT_VERSION = b'\x01'
STANZA_FORMAT_VERSION = b'\x01'
FIDO2_RELYING_PARTY = 'example.com'
WAIT_FOR_DEVICE_TIMEOUT = 120

# => create_identity(bytes('fido2-hmac', 'utf-8'), False)
MAGIC_IDENTITY = 'AGE-PLUGIN-FIDO2-HMAC-1QYQXV6TYDUEZ66RDV93SQUSDAT'
