package plugin

import (
	"crypto/rand"
	"fmt"
	"os"
	"strings"
	"time"

	"filippo.io/age"
	page "filippo.io/age/plugin"
	"github.com/olastor/go-libfido2"
)

// CredentialsResult holds all the recipients and identity generated by NewCredentials.
type CredentialsResult struct {
	X25519Recipient    *age.X25519Recipient
	HybridRecipient    *age.HybridRecipient
	Fido2HmacRecipient *Fido2HmacRecipient
	Fido2HmacIdentity  *Fido2HmacIdentity
}

// Generates a new credential and returns recipient(s) and identity
// based on the user's responses (each may be nil). If `askForIdentity`
// is false, it's assumed that no identity shall be generated.
func NewCredentials(
	algorithm libfido2.CredentialType,
	symmetric bool,
	pq bool,
	ui *page.ClientUI,
	askForIdentity bool,
) (result CredentialsResult, err error) {
	var device Fido2Device

	displayMessage := func(message string) error {
		return ui.DisplayMessage(PLUGIN_NAME, message)
	}

	err = displayMessage("Please insert your token now...\n")
	if err != nil {
		return
	}

	device, err = FindDevice(50*time.Second, displayMessage)
	if err != nil {
		return
	}

	hasPinSet, err := device.HasPinSet()
	if err != nil {
		return
	}

	pin := ""
	if hasPinSet {
		pin, err = ui.RequestValue(PLUGIN_NAME, "Please enter your PIN:", true)
		if err != nil {
			return
		}
	}

	err = displayMessage("Please touch your token...\n")
	if err != nil {
		return
	}
	credId, err := device.GenerateCredential(pin, algorithm)
	if err != nil {
		return
	}

	requirePin := false
	if hasPinSet {
		requirePin, err = ui.Confirm(PLUGIN_NAME, "Do you want to require a PIN for decryption?", "yes", "no")
		if err != nil {
			return
		}
	}

	if !requirePin {
		pin = ""
	}

	wantsSeparateIdentity := false
	if askForIdentity {
		wantsSeparateIdentity, err = ui.Confirm(
			PLUGIN_NAME,
			"Are you fine with having a separate identity (better privacy)?\n",
			"yes",
			"no",
		)

		if err != nil {
			return
		}
	}

	if symmetric {
		result.Fido2HmacIdentity = &Fido2HmacIdentity{
			Version:    1,
			RequirePin: requirePin,
			Salt:       nil,
			CredId:     credId,
			Device:     device,
			UI:         ui,
		}

		result.Fido2HmacRecipient, err = result.Fido2HmacIdentity.Recipient()
		if err != nil {
			return
		}

		if !wantsSeparateIdentity {
			result.Fido2HmacIdentity = nil
		}

		return
	}

	salt := make([]byte, 32)
	if _, err = rand.Read(salt); err != nil {
		return
	}

	result.Fido2HmacIdentity = &Fido2HmacIdentity{
		Version:    2,
		PQ:         pq,
		RequirePin: requirePin,
		Salt:       salt,
		CredId:     credId,
		Device:     device,
		UI:         ui,
	}

	_, err = result.Fido2HmacIdentity.obtainSecretFromToken(pin)
	if err != nil {
		return
	}

	result.Fido2HmacRecipient, err = result.Fido2HmacIdentity.Recipient()
	if err != nil {
		return
	}

	if !wantsSeparateIdentity {
		result.Fido2HmacIdentity.ClearSecret()
		result.Fido2HmacIdentity = nil
		return
	}

	// include the hybrid recipient anyways because it's almost free and can be shown optionally
	var hybridIdentity *age.HybridIdentity
	hybridIdentity, err = result.Fido2HmacIdentity.HybridIdentity()
	if err != nil {
		return
	}

	result.HybridRecipient = hybridIdentity.Recipient()

	if !pq {
		result.X25519Recipient, err = result.Fido2HmacRecipient.X25519Recipient()
		if err != nil {
			return
		}
	}

	result.Fido2HmacIdentity.ClearSecret()
	result.Fido2HmacRecipient = nil

	return
}

const defaultPrintfPrefix = "%s plugin: "

func NewCredentialsCli(
	algorithm libfido2.CredentialType,
	symmetric bool,
	pq bool,
) (result CredentialsResult, err error) {
	printf := func(format string, v ...any) {
		if strings.HasPrefix(format, defaultPrintfPrefix) {
			// try to use a nicer prefix if possible
			newFormat := strings.Replace(format, defaultPrintfPrefix, "[*] ", 1)
			fmt.Fprintf(os.Stderr, newFormat, v[1:]...)
			return
		}

		fmt.Fprintf(os.Stderr, format, v...)
	}
	warningf := func(format string, v ...any) {
		fmt.Fprintf(os.Stderr, format, v...)
	}
	ui := page.NewTerminalUI(printf, warningf)

	return NewCredentials(
		algorithm,
		symmetric,
		pq,
		ui,
		true,
	)
}
